/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista.inicio;

/**
 *
 * @author lp-ub-14
 */
public class JD_acercade extends javax.swing.JDialog {

    /**
     * Creates new form JD_acercade
     */
    public JD_acercade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_inicio3 = new javax.swing.JLabel();
        jl_inicio2 = new javax.swing.JLabel();
        jl_inicio1 = new javax.swing.JLabel();
        jl_iniciosub2 = new javax.swing.JLabel();
        jl_iniciosub1 = new javax.swing.JLabel();
        jl_inicio6 = new javax.swing.JLabel();
        jl_inicio7 = new javax.swing.JLabel();
        jl_inicio8 = new javax.swing.JLabel();
        jl_inicio9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jl_inicio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_inicio3.setText("evolución de tus proyectos.");

        jl_inicio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_inicio2.setText("llevar un seguimiento de la ");

        jl_inicio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_inicio1.setText("Aquí podrás tener tus Test de Usabilidad  y");

        jl_iniciosub2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jl_iniciosub2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_iniciosub2.setText("(Evaluación Interactiva de Usabilidad)");

        jl_iniciosub1.setFont(new java.awt.Font("Ubuntu", 1, 32)); // NOI18N
        jl_iniciosub1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_iniciosub1.setText("EVIU");

        jl_inicio6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_inicio6.setText("Miguel Castillo Cortes");

        jl_inicio7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_inicio7.setText("Rafael Eduardo Méndez Pérez");

        jl_inicio8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_inicio8.setText("Daniel Chávez Vilchi");

        jl_inicio9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jl_inicio9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_inicio9.setText("Programadores:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_iniciosub1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_iniciosub2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_inicio1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jl_inicio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_inicio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_inicio6, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jl_inicio9, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
            .addComponent(jl_inicio8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jl_inicio7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_iniciosub1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_iniciosub2)
                .addGap(63, 63, 63)
                .addComponent(jl_inicio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_inicio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_inicio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jl_inicio9)
                .addGap(18, 18, 18)
                .addComponent(jl_inicio8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_inicio7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_inicio6)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_acercade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_acercade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_acercade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_acercade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JD_acercade dialog = new JD_acercade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_inicio1;
    private javax.swing.JLabel jl_inicio2;
    private javax.swing.JLabel jl_inicio3;
    private javax.swing.JLabel jl_inicio6;
    private javax.swing.JLabel jl_inicio7;
    private javax.swing.JLabel jl_inicio8;
    private javax.swing.JLabel jl_inicio9;
    private javax.swing.JLabel jl_iniciosub1;
    private javax.swing.JLabel jl_iniciosub2;
    // End of variables declaration//GEN-END:variables
}
