package vista.abrirProyecto;

public class JP_iconoTest extends javax.swing.JPanel {

    String nomTest;
    JP_proyectoAbierto JP_proyectoAbierto;

    public JP_iconoTest(String nomTest, JP_proyectoAbierto JP_proyectoAbierto) {
        this.nomTest = nomTest;
        this.JP_proyectoAbierto = JP_proyectoAbierto;

        this.setSize(140, 144);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jimPop_eliminarTest = new javax.swing.JMenuItem();
        jimPop_borrarRespuestas = new javax.swing.JMenuItem();
        jl_icono = new javax.swing.JLabel();
        jl_nomTest = new javax.swing.JLabel();

        jPopupMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jimPop_eliminarTest.setText("Eliminar Test");
        jimPop_eliminarTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimPop_eliminarTestActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jimPop_eliminarTest);

        jimPop_borrarRespuestas.setText("Borrar Respuestas");
        jimPop_borrarRespuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimPop_borrarRespuestasActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jimPop_borrarRespuestas);

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jl_icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Test.png"))); // NOI18N
        jl_icono.setComponentPopupMenu(jPopupMenu1);
        jl_icono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_iconoMouseClicked(evt);
            }
        });

        jl_nomTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_nomTest.setText(nomTest);
        jl_nomTest.setComponentPopupMenu(jPopupMenu1);
        jl_nomTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_nomTestMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_icono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_nomTest, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_nomTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jl_iconoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_iconoMouseClicked
        seleccionado();
    }//GEN-LAST:event_jl_iconoMouseClicked

    private void jl_nomTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_nomTestMouseClicked
        seleccionado();
    }//GEN-LAST:event_jl_nomTestMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        seleccionado();
    }//GEN-LAST:event_formMouseClicked

    private void jimPop_borrarRespuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimPop_borrarRespuestasActionPerformed
        String nomP = JP_proyectoAbierto.getStr_nomProyecto();

        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = javax.swing.JOptionPane.showOptionDialog(JP_proyectoAbierto,
                "Esta realmente seguro de eliminar las respuestas de este Test",
                "Mensaje de confirmación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == javax.swing.JOptionPane.YES_OPTION) {
            boolean a = controlador.Archivos.borrarRespuestas(nomP, nomTest);
            if (a) {
                javax.swing.JOptionPane.showMessageDialog(
                        null,
                        "Las Respuestas de este Test se han borrado satisfactoriamente");
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                        null,
                        "Error");
            }
        }


    }//GEN-LAST:event_jimPop_borrarRespuestasActionPerformed

    private void jimPop_eliminarTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimPop_eliminarTestActionPerformed
        javax.swing.JOptionPane.showMessageDialog(null, "Debe Eliminar el test \n Aun no implementado");
    }//GEN-LAST:event_jimPop_eliminarTestActionPerformed
    private void seleccionado() {
        JP_iconoTest JP_iconoTest = JP_proyectoAbierto.getJP_iconoTest();
        if (JP_iconoTest != null) {
            JP_iconoTest.setBackground(null);
        }
        this.setBackground(vista.Config.colorDeSeleccionado());
        JP_proyectoAbierto.setJP_iconoTest(this);
        JP_proyectoAbierto.setStr_nomTest(jl_nomTest.getText());
        JP_proyectoAbierto.activarBotonAbrir();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem jimPop_borrarRespuestas;
    private javax.swing.JMenuItem jimPop_eliminarTest;
    private javax.swing.JLabel jl_icono;
    private javax.swing.JLabel jl_nomTest;
    // End of variables declaration//GEN-END:variables
}
