/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista.abrirProyecto;

public class JP_proyectoAbierto extends javax.swing.JPanel {
    vista.Eviu Eviu;
    JP_iconoTest JP_iconoTest;
    String str_nomProyecto;
    String str_nomTest;
    public JP_proyectoAbierto(String nombreProyecto, vista.Eviu Eviu) {
        str_nomProyecto=nombreProyecto;
        initComponents();
        this.Eviu=Eviu;
        this.setSize(900, 577);
        font();
        jp_contenedor.setMaximumSize ( new java.awt.Dimension ( 657, 356 ) );
        jp_contenedor.setMinimumSize ( new java.awt.Dimension ( 600, 300 ) );
        
        jScrollPane1.setMaximumSize ( new java.awt.Dimension ( 657, 356 ) );
        jScrollPane1.setMinimumSize ( new java.awt.Dimension ( 600, 300 ) );
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_nomProyecto = new javax.swing.JLabel();
        jl_subtitulo = new javax.swing.JLabel();
        jb_abrir = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jp_contenedor = new javax.swing.JPanel();

        jl_nomProyecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_nomProyecto.setText("Proyecto: "+str_nomProyecto);

        jl_subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_subtitulo.setText("Tienes los siguientes Tests en este Proyecto.");

        jb_abrir.setText("Abrir");
        jb_abrir.setEnabled(false);
        jb_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_abrirActionPerformed(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");

        jp_contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        seticonoTest();
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEADING);
        flowLayout1.setAlignOnBaseline(true);
        jp_contenedor.setLayout(flowLayout1);
        jScrollPane1.setViewportView(jp_contenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1)))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jl_nomProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jl_subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jl_nomProyecto)
                .addGap(18, 18, 18)
                .addComponent(jl_subtitulo)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        Eviu.pintarPanelInicio();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_abrirActionPerformed
        Eviu.bloquearVentanaPrincipal();
        vista.perfil.JD_perfil.main(Eviu,str_nomProyecto);
        Eviu.pintarPanel_test(str_nomProyecto,str_nomTest);
    }//GEN-LAST:event_jb_abrirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_abrir;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JLabel jl_nomProyecto;
    private javax.swing.JLabel jl_subtitulo;
    private javax.swing.JPanel jp_contenedor;
    // End of variables declaration//GEN-END:variables
    private void font() {
        jl_subtitulo.setFont(vista.Config.getTam_subTitulo());
        jl_nomProyecto.setFont(vista.Config.getTam_Titulo());
    }
    public void seticonoTest() {
        java.util.ArrayList<String> lst_Tests = controlador.Archivos.getTests(str_nomProyecto);
        for(String test:lst_Tests){
            jp_contenedor.add(new JP_iconoTest(test,this));
        }
        
    }

    public JP_iconoTest getJP_iconoTest() {
        return JP_iconoTest;
    }

    public void setJP_iconoTest(JP_iconoTest JP_iconoTest) {
        this.JP_iconoTest = JP_iconoTest;
    }

    public String getStr_nomTest() {
        return str_nomTest;
    }

    public void setStr_nomTest(String str_nomTest) {
        this.str_nomTest = str_nomTest;
    }
    public void activarBotonAbrir(){
        jb_abrir.setEnabled(true);
    }
}
